name: Hello World Training Workflow

on:
  workflow_dispatch:
 
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the User
        run: echo "Hello World!"
      - name: List Files in Directory
        run: ls -l
      - name: Checkout Code
        uses: actions/checkout@v2
